#### The is Neva's starter notebook.  A "scratch pad", so to speak.
- below is code for creating a dataframe of state-level data  `states_raw.csv`

https://github.com/GoogleCloudPlatform/covid-19-open-data

In [2]:
import pandas as pd
# raw = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v2/main.csv", low_memory=False)

Problem Statement:
Identify potential Covid hotspots, specifically predict CASES based on government actions, population data, geography, and key health indicators.
Data sets we will use:  
1. Covid19 database on GitHub - https://github.com/GoogleCloudPlatform/covid-19-open-data
1. Shape files from US Census

In [3]:
raw.shape

(6072300, 108)

In [4]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6072300 entries, 0 to 6072299
Columns: 108 entries, key to relative_humidity
dtypes: float64(93), int64(1), object(14)
memory usage: 4.9+ GB

In [13]:
# raw.to_csv('raw_download.csv')

In [3]:
# raw = pd.read_csv('raw_download.csv', )     #index_col=False, 

#     parse_dates=False,
#     infer_datetime_format=False,
#     keep_date_col=False,
#     date_parser=None,

/Users/nevochka/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (3,4,7,9,10,11,12) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
raw.columns.tolist()

['key',
 'date',
 'wikidata',
 'datacommons',
 'country_code',
 'country_name',
 'subregion1_code',
 'subregion1_name',
 'subregion2_code',
 'subregion2_name',
 'locality_code',
 'locality_name',
 '3166-1-alpha-2',
 '3166-1-alpha-3',
 'aggregation_level',
 'new_confirmed',
 'new_deceased',
 'new_recovered',
 'new_tested',
 'total_confirmed',
 'total_deceased',
 'total_recovered',
 'total_tested',
 'new_hospitalized',
 'total_hospitalized',
 'current_hospitalized',
 'new_intensive_care',
 'total_intensive_care',
 'current_intensive_care',
 'new_ventilator',
 'total_ventilator',
 'current_ventilator',
 'population',
 'population_male',
 'population_female',
 'rural_population',
 'urban_population',
 'largest_city_population',
 'clustered_population',
 'population_density',
 'human_development_index',
 'population_age_00_09',
 'population_age_10_19',
 'population_age_20_29',
 'population_age_30_39',
 'population_age_40_49',
 'population_age_50_59',
 'population_age_60_69',
 'population_age_70_79',
 'population_age_80_89',
 'population_age_90_99',
 'population_age_80_and_older',
 'gdp',
 'gdp_per_capita',
 'human_capital_index',
 'open_street_maps',
 'latitude',
 'longitude',
 'elevation',
 'area',
 'rural_area',
 'urban_area',
 'life_expectancy',
 'smoking_prevalence',
 'diabetes_prevalence',
 'infant_mortality_rate',
 'adult_male_mortality_rate',
 'adult_female_mortality_rate',
 'pollution_mortality_rate',
 'comorbidity_mortality_rate',
 'hospital_beds',
 'nurses',
 'physicians',
 'health_expenditure',
 'out_of_pocket_health_expenditure',
 'mobility_retail_and_recreation',
 'mobility_grocery_and_pharmacy',
 'mobility_parks',
 'mobility_transit_stations',
 'mobility_workplaces',
 'mobility_residential',
 'school_closing',
 'workplace_closing',
 'cancel_public_events',
 'restrictions_on_gatherings',
 'public_transport_closing',
 'stay_at_home_requirements',
 'restrictions_on_internal_movement',
 'international_travel_controls',
 'income_support',
 'debt_relief',
 'fiscal_measures',
 'international_support',
 'public_information_campaigns',
 'testing_policy',
 'contact_tracing',
 'emergency_investment_in_healthcare',
 'investment_in_vaccines',
 'stringency_index',
 'noaa_station',
 'noaa_distance',
 'average_temperature',
 'minimum_temperature',
 'maximum_temperature',
 'rainfall',
 'snowfall',
 'dew_point',
 'relative_humidity']

In [5]:
pd.set_option("display.max_columns", 120)
pd.set_option("display.max_rows", 120)

raw.head(5).T

,0,1,2,3,4
Unnamed: 0,0,1,2,3,4
key,AD,AD,AD,AD,AD
date,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05
wikidata,Q228,Q228,Q228,Q228,Q228
datacommons,country/AND,country/AND,country/AND,country/AND,country/AND
country_code,AD,AD,AD,AD,AD
country_name,Andorra,Andorra,Andorra,Andorra,Andorra
subregion1_code,NaN,NaN,NaN,NaN,NaN
subregion1_name,NaN,NaN,NaN,NaN,NaN
subregion2_code,NaN,NaN,NaN,NaN,NaN
subregion2_name,NaN,NaN,NaN,NaN,NaN
locality_code,NaN,NaN,NaN,NaN,NaN
locality_name,NaN,NaN,NaN,NaN,NaN
3166-1-alpha-2,AD,AD,AD,AD,AD
3166-1-alpha-3,AND,AND,AND,AND,AND
aggregation_level,0,0,0,0,0
new_confirmed,NaN,0,0,0,0
new_deceased,NaN,0,0,0,0
new_recovered,NaN,NaN,NaN,NaN,NaN
new_tested,NaN,NaN,NaN,NaN,NaN
total_confirmed,NaN,0,0,0,0
total_deceased,NaN,0,0,0,0
total_recovered,NaN,NaN,NaN,NaN,NaN
total_tested,NaN,NaN,NaN,NaN,NaN
new_hospitalized,NaN,NaN,NaN,NaN,NaN
total_hospitalized,NaN,NaN,NaN,NaN,NaN
current_hospitalized,NaN,NaN,NaN,NaN,NaN
new_intensive_care,NaN,NaN,NaN,NaN,NaN
total_intensive_care,NaN,NaN,NaN,NaN,NaN
current_intensive_care,NaN,NaN,NaN,NaN,NaN
new_ventilator,NaN,NaN,NaN,NaN,NaN
total_ventilator,NaN,NaN,NaN,NaN,NaN
current_ventilator,NaN,NaN,NaN,NaN,NaN
population,77142,77142,77142,77142,77142
population_male,58625,58625,58625,58625,58625
population_female,55581,55581,55581,55581,55581
rural_population,9269,9269,9269,9269,9269
urban_population,67873,67873,67873,67873,67873
largest_city_population,NaN,NaN,NaN,NaN,NaN
clustered_population,NaN,NaN,NaN,NaN,NaN
population_density,163.843,163.843,163.843,163.843,163.843
human_development_index,0.858,0.858,0.858,0.858,0.858
population_age_00_09,9370,9370,9370,9370,9370
population_age_10_19,12022,12022,12022,12022,12022
population_age_20_29,10727,10727,10727,10727,10727
population_age_30_39,12394,12394,12394,12394,12394
population_age_40_49,21001,21001,21001,21001,21001
population_age_50_59,20720,20720,20720,20720,20720
population_age_60_69,14433,14433,14433,14433,14433
population_age_70_79,8657,8657,8657,8657,8657
population_age_80_89,3904,3904,3904,3904,3904
population_age_90_99,976,976,976,976,976
population_age_80_and_older,4881,4881,4881,4881,4881
gdp,3.15406e+09,3.15406e+09,3.15406e+09,3.15406e+09,3.15406e+09
gdp_per_capita,40886,40886,40886,40886,40886
human_capital_index,NaN,NaN,NaN,NaN,NaN
open_street_maps,9407,9407,9407,9407,9407
latitude,42.5583,42.5583,42.5583,42.5583,42.5583
longitude,1.55528,1.55528,1.55528,1.55528,1.55528
elevation,NaN,NaN,NaN,NaN,NaN
area,470,470,470,470,470
rural_area,NaN,NaN,NaN,NaN,NaN
urban_area,NaN,NaN,NaN,NaN,NaN
life_expectancy,NaN,NaN,NaN,NaN,NaN
smoking_prevalence,33.5,33.5,33.5,33.5,33.5
diabetes_prevalence,7.7,7.7,7.7,7.7,7.7
infant_mortality_rate,2.7,2.7,2.7,2.7,2.7
adult_male_mortality_rate,NaN,NaN,NaN,NaN,NaN
adult_female_mortality_rate,NaN,NaN,NaN,NaN,NaN
pollution_mortality_rate,NaN,NaN,NaN,NaN,NaN
comorbidity_mortality_rate,NaN,NaN,NaN,NaN,NaN
hospital_beds,NaN,NaN,NaN,NaN,NaN
nurses,4.0128,4.0128,4.0128,4.0128,4.0128
physicians,3.3333,3.3333,3.3333,3.3333,3.3333
health_expenditure,4040.79,4040.79,4040.79,4040.79,4040.79
out_of_pocket_health_expenditure,1688.12,1688.12,1688.12,1688.12,1688.12
mobility_retail_and_recreation,NaN,NaN,NaN,NaN,NaN
mobility_grocery_and_pharmacy,NaN,NaN,NaN,NaN,NaN
mobility_parks,NaN,NaN,NaN,NaN,NaN
mobility_transit_stations,NaN,NaN,NaN,NaN,NaN
mobility_workplaces,NaN,NaN,NaN,NaN,NaN
mobility_residential,NaN,NaN,NaN,NaN,NaN
school_closing,0,0,0,0,0
workplace_closing,0,0,0,0,0
cancel_public_events,0,0,0,0,0
restrictions_on_gatherings,0,0,0,0,0
public_transport_closing,0,0,0,0,0
stay_at_home_requirements,0,0,0,0,0
restrictions_on_internal_movement,0,0,0,0,0
international_travel_controls,0,0,0,0,0
income_support,0,0,0,0,0
debt_relief,0,0,0,0,0
fiscal_measures,0,0,0,0,0
international_support,0,0,0,0,0
public_information_campaigns,0,0,0,0,0
testing_policy,0,0,0,0,0
contact_tracing,0,0,0,0,0
emergency_investment_in_healthcare,0,0,0,0,0
investment_in_vaccines,0,0,0,0,0
stringency_index,0,0,0,0,0
noaa_station,NaN,NaN,NaN,NaN,NaN
noaa_distance,NaN,NaN,NaN,NaN,NaN
average_temperature,NaN,NaN,NaN,NaN,NaN
minimum_temperature,NaN,NaN,NaN,NaN,NaN
maximum_temperature,NaN,NaN,NaN,NaN,NaN
rainfall,NaN,NaN,NaN,NaN,NaN
snowfall,NaN,NaN,NaN,NaN,NaN
dew_point,NaN,NaN,NaN,NaN,NaN
relative_humidity,NaN,NaN,NaN,NaN,NaN

In [6]:
raw.shape

(5962245, 109)

In [74]:
df_state = raw.loc[raw['key'] == 'US_SD']
df_state.shape

(300, 108)

In [75]:
df_state.head(3)

,key,date,wikidata,datacommons,country_code,country_name,subregion1_code,subregion1_name,subregion2_code,subregion2_name,...,stringency_index,noaa_station,noaa_distance,average_temperature,minimum_temperature,maximum_temperature,rainfall,snowfall,dew_point,relative_humidity
5797500,US_SD,2020-01-01,Q1211,geoId/46,US,United States of America,SD,South Dakota,NaN,NaN,...,0.0,7.265602e+10,26.288294,-2.427778,-9.255556,3.966667,0.0000,279.400,-6.729167,72.885727
5797501,US_SD,2020-01-02,Q1211,geoId/46,US,United States of America,SD,South Dakota,NaN,NaN,...,0.0,7.265602e+10,26.288294,1.594444,-3.527778,4.283333,0.9906,272.415,-0.694444,83.373710
5797502,US_SD,2020-01-03,Q1211,geoId/46,US,United States of America,SD,South Dakota,NaN,NaN,...,0.0,7.265602e+10,26.288294,-0.322222,-5.166667,3.083333,0.2540,227.330,-3.937500,75.925394

In [76]:
df_state['subregion2_name']

5797500    NaN
5797501    NaN
5797502    NaN
5797503    NaN
5797504    NaN
          ...
5797795    NaN
5797796    NaN
5797797    NaN
5797798    NaN
5797799    NaN
Name: subregion2_name, Length: 300, dtype: object

In [77]:
# df_state.to_csv('./data/state_sd.csv')
# df_state.to_csv('./data/state_nd.csv')
# df_state.to_csv('./data/state_ks.csv')
# df_state.to_csv('./data/state_ne.csv')
# df_state.to_csv('./data/state_ok.csv')
# df_state.to_csv('./data/state_tx.csv')
# df_state.to_csv('./data/state_nm.csv')
# df_state.to_csv('./data/state_co.csv')
# df_state.to_csv('./data/state_ut.csv')
# df_state.to_csv('./data/state_wy.csv')
# df_state.to_csv('./data/state_nv.csv')
# df_state.to_csv('./data/state_ca.csv')
# df_state.to_csv('./data/state_or.csv')
# df_state.to_csv('./data/state_wa.csv')
# df_state.to_csv('./data/state_id.csv')
# df_state.to_csv('./data/state_mt.csv')

In [79]:
x = 300 * 15
x

4500

In [148]:
state_input = pd.read_csv('./data/state_wy.csv')
state_input.shape

(300, 109)

In [149]:
state_input.head(3)

,Unnamed: 0,key,date,wikidata,datacommons,country_code,country_name,subregion1_code,subregion1_name,subregion2_code,...,stringency_index,noaa_station,noaa_distance,average_temperature,minimum_temperature,maximum_temperature,rainfall,snowfall,dew_point,relative_humidity
0,6028500,US_WY,2020-01-01,Q1214,geoId/56,US,United States of America,WY,Wyoming,NaN,...,0.0,7.267202e+10,78.296276,-2.825397,-10.428571,3.944444,0.217714,127.0,-9.111111,64.920419
1,6028501,US_WY,2020-01-02,Q1214,geoId/56,US,United States of America,WY,Wyoming,NaN,...,0.0,7.267202e+10,78.296276,-1.595238,-6.761905,3.928571,0.907143,127.0,-6.944444,67.982575
2,6028502,US_WY,2020-01-03,Q1214,geoId/56,US,United States of America,WY,Wyoming,NaN,...,0.0,7.267202e+10,78.296276,-3.746032,-9.738095,3.428571,0.000000,127.0,-9.601852,64.983958

In [150]:
# concat state-level data into one df, uncomment to revise

# states_raw = pd.concat([state_input, states_raw])
# states_raw.shape

(4800, 109)

In [151]:
states_raw['subregion1_name'].value_counts()

California      300
Nebraska        300
South Dakota    300
Utah            300
New Mexico      300
Oregon          300
North Dakota    300
Colorado        300
Montana         300
Kansas          300
Oklahoma        300
Texas           300
Washington      300
Idaho           300
Wyoming         300
Nevada          300
Name: subregion1_name, dtype: int64

In [152]:
# save state-level data into file, uncomment to revise

# states_raw.to_csv('./data/states_raw.csv')

In [156]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [175]:
states_raw.loc[states_raw['subregion1_code'] == 'CO'].isna().sum()

Unnamed: 0                              0
key                                     0
date                                    0
wikidata                                0
datacommons                             0
country_code                            0
country_name                            0
subregion1_code                         0
subregion1_name                         0
subregion2_code                       300
subregion2_name                       300
locality_code                         300
locality_name                         300
3166-1-alpha-2                          0
3166-1-alpha-3                          0
aggregation_level                       0
new_confirmed                          67
new_deceased                           67
new_recovered                         118
new_tested                             67
total_confirmed                        66
total_deceased                         66
total_recovered                       117
total_tested                           66
new_hospitalized                       86
total_hospitalized                     85
current_hospitalized                   86
new_intensive_care                    300
total_intensive_care                  300
current_intensive_care                300
new_ventilator                        300
total_ventilator                      300
current_ventilator                    300
population                              0
population_male                         0
population_female                       0
rural_population                      300
urban_population                      300
largest_city_population               300
clustered_population                  300
population_density                    300
human_development_index               300
population_age_00_09                    0
population_age_10_19                    0
population_age_20_29                    0
population_age_30_39                    0
population_age_40_49                    0
population_age_50_59                    0
population_age_60_69                    0
population_age_70_79                    0
population_age_80_89                    0
population_age_90_99                    0
population_age_80_and_older             0
gdp                                   300
gdp_per_capita                        300
human_capital_index                   300
open_street_maps                        0
latitude                                0
longitude                               0
elevation                               0
area                                    0
rural_area                            300
urban_area                            300
life_expectancy                       300
smoking_prevalence                    300
diabetes_prevalence                   300
infant_mortality_rate                 300
adult_male_mortality_rate             300
adult_female_mortality_rate           300
pollution_mortality_rate              300
comorbidity_mortality_rate            300
hospital_beds                         300
nurses                                300
physicians                            300
health_expenditure                    300
out_of_pocket_health_expenditure      300
mobility_retail_and_recreation         53
mobility_grocery_and_pharmacy          53
mobility_parks                         53
mobility_transit_stations              53
mobility_workplaces                    53
mobility_residential                   53
school_closing                         20
workplace_closing                      20
cancel_public_events                   20
restrictions_on_gatherings             20
public_transport_closing               20
stay_at_home_requirements              20
restrictions_on_internal_movement      20
international_travel_controls          20
income_support                         11
debt_relief                            20
fiscal_measures                       300
international_support                 300
public_information_campaigns           20
testing_policy                         20
contact_tracing                        20
emergency_investment_in_healthcare    300
investment_in_vaccines                300
stringency_index                       20
noaa_station                            5
noaa_distance                           5
average_temperature                     5
minimum_temperature                     5
maximum_temperature                     5
rainfall                                5
snowfall                              268
dew_point                               5
relative_humidity                       5
dtype: int64